services:
  registry:
    image: registry:3
    container_name: registry-test
    restart: unless-stopped
    environment:
      - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/data
      - REGISTRY_STORAGE_DELETE_ENABLED=true
      - REGISTRY_AUTH=htpasswd
      - REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm
      - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
      - REGISTRY_HTTP_RELATIVEURLS=true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.registry-test.rule=Host(`${REGISTRY_HOST}`)"
      - "traefik.http.routers.registry-test.entrypoints=web"
      - "traefik.http.services.registry-test.loadbalancer.server.port=5000"
    volumes:
      - registry-data:/data
      - /home/test/registry/auth:/auth:ro
    networks:
      - proxy
  registry-ui:
    image: joxit/docker-registry-ui:latest
    container_name: registry-ui-test
    restart: unless-stopped
    environment:
      - SINGLE_REGISTRY=true
      - REGISTRY_TITLE=Docker Registry
      - DELETE_IMAGES=true
      - SHOW_CONTENT_DIGEST=true
      - NGINX_PROXY_PASS_URL=http://registry:5000
      - SHOW_CATALOG_NB_TAGS=true
      - CATALOG_MIN_BRANCHES=1
      - CATALOG_MAX_BRANCHES=1
      - TAGLIST_PAGE_SIZE=100
      - REGISTRY_SECURED=true
      - CATALOG_ELEMENTS_LIMIT=1000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.registry-ui-test.rule=Host(`${REGISTRY_UI_HOST}`)"
      - "traefik.http.routers.registry-ui-test.entrypoints=web"
      - "traefik.http.services.registry-ui-test.loadbalancer.server.port=80"
    depends_on:
      - registry
    networks:
      - proxy

volumes:
  registry-data:

networks:
  proxy:
    external: true
