services:
  drone-server:
    image: drone/drone:2
    container_name: drone-server-test
    restart: unless-stopped
    environment:
      - DRONE_GITHUB_CLIENT_ID=${DRONE_GITHUB_CLIENT_ID}
      - DRONE_GITHUB_CLIENT_SECRET=${DRONE_GITHUB_CLIENT_SECRET}
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
      - DRONE_SERVER_HOST=${DRONE_SERVER_HOST}
      - DRONE_SERVER_PROTO=https
      - DRONE_DATABASE_DRIVER=sqlite3
      - DRONE_DATABASE_DATASOURCE=/data/database.sqlite
      - DRONE_USER_CREATE=username:${GITHUB_USERNAME},admin:true
      - DRONE_USER_FILTER=${GITHUB_USERNAME}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.drone-test.rule=Host(`${DRONE_SERVER_HOST}`)"
      - "traefik.http.services.drone-test.loadbalancer.server.port=80"
      - "traefik.http.routers.drone-test.entrypoints=web"
    volumes:
      - drone-test-data:/data
    networks:
      - proxy
  drone-runner:
    image: drone/drone-runner-docker:1
    container_name: drone-runner-test
    restart: unless-stopped
    environment:
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
      - DRONE_RPC_HOST=drone-server
      - DRONE_RPC_PROTO=http
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_RUNNER_NAME=drone-test-runner
      - DRONE_RUNNER_NETWORKS=proxy
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy
  backup-prepare:
    image: alpine:latest
    container_name: drone-backup-prepare
    restart: unless-stopped
    volumes:
      - drone-test-backup:/dumps
      - drone-test-data:/data
    entrypoint: sh -c "apk add sqlite && echo '30 1 * * * sqlite3 /data/database.sqlite .backup > /dumps/database-backup.sqlite' | crontab - && crond -f -l 2"
  backup-cloud:
    image: mazzolino/restic:latest
    container_name: drone-backup-cloud
    restart: unless-stopped
    environment:
      - BACKUP_CRON=30 2 * * *
      - RESTIC_REPOSITORY=${RESTIC_REPOSITORY}/drone
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - RESTIC_PASSWORD=${RESTIC_PASSWORD}
      - RESTIC_BACKUP_ARGS=--verbose --tag drone
      - RESTIC_FORGET_ARGS=--keep-daily 7 --keep-weekly 4 --keep-monthly 6
      - TZ=Europe/Warsaw
    depends_on:
      - backup-prepare
    volumes:
      - drone-test-backup:/data/dumps:ro
      - ./:/data/docker:ro
volumes:
  drone-test-data:
  drone-test-backup:
networks:
  proxy:
    external: true
