services:
  api:
    image: ${REGISTRY_URL}/api-test-${ENV}:latest
    container_name: test-api-${ENV}
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.test-api-${ENV}.rule=Host(`${HOST}`) && PathPrefix(`${API_PREFIX}`)"
      - "traefik.http.services.test-api-${ENV}.loadbalancer.server.port=3000"
      - "traefik.http.routers.test-api-${ENV}.middlewares=strip-api"
      - "traefik.http.middlewares.strip-api.stripprefix.prefixes=${API_PREFIX}"
    depends_on:
      migrate:
        condition: service_completed_successfully
    networks:
      - proxy
      - test-internal
  client:
    image: ${REGISTRY_URL}/client-test-${ENV}:latest
    container_name: test-client-${ENV}
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.test-${ENV}.rule=Host(`${HOST}`)"
      - "traefik.http.routers.test-${ENV}.priority=1"
      - "traefik.http.services.test-${ENV}.loadbalancer.server.port=80"
    networks:
      - proxy
  db:
    image: postgres:16-alpine
    container_name: test-db-${ENV}
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - test-internal
    volumes:
      - test-volume:/var/lib/postgresql/data
  migrate:
    build: ./api
    container_name: test-migrate-${ENV}
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    command: bunx prisma migrate deploy
    networks:
      - test-internal
networks:
  proxy:
    external: true
